// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ConcesionariaVehiculos.Data;

#nullable disable

namespace ConcesionariaVehiculos.Migrations
{
	[DbContext(typeof(AppDbContext))]
	[Migration("20250318012736_AjusteFluentAPI")]
	partial class AjusteFluentAPI
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.13")
				.HasAnnotation("Relational:MaxIdentifierLength", 64);

			MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

			modelBuilder.Entity("ConcesionariaVehiculos.Cliente", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("Nombre")
					.IsRequired()
					.HasColumnType("longtext");

				b.Property<string>("Apellido")
					.IsRequired()
					.HasColumnType("longtext");

				b.Property<string>("Telefono")
					.IsRequired()
					.HasColumnType("longtext");

				b.Property<string>("Email")
					.IsRequired()
					.HasColumnType("longtext");

				b.HasKey("Id");

				b.ToTable("Clientes");
			});

			modelBuilder.Entity("ConcesionariaVehiculos.Models.Vehiculo", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("Marca")
					.IsRequired()
					.HasMaxLength(50)
					.HasColumnType("varchar(50)");

				b.Property<string>("Modelo")
					.IsRequired()
					.HasMaxLength(50)
					.HasColumnType("varchar(50)");

				b.Property<int>("Año")
					.HasColumnType("int");

				b.Property<decimal>("Precio")
					.HasPrecision(10, 2)
					.HasColumnType("decimal(10,2)");

				b.Property<int>("Stock")
					.HasColumnType("int");

				b.HasKey("Id");

				b.ToTable("Vehiculos");
			});
			modelBuilder.Entity("ConcesionariaVehiculos.Venta", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

				b.Property<int>("ClienteId")
					.HasColumnType("int");

				b.Property<DateTime>("Fecha")
					.HasColumnType("datetime(6)");

				b.Property<decimal>("Total")
					.HasPrecision(10, 2)
					.HasColumnType("decimal(10,2)");

				b.Property<int>("VehiculoId")
					.HasColumnType("int");

				b.HasKey("Id");

				b.HasIndex("ClienteId");

				b.HasIndex("VehiculoId");

				b.ToTable("Ventas");
			});
			modelBuilder.Entity("ConcesionariaVehiculos.Models.ServicioPosVenta", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

				b.Property<string>("TipoServicio")
					.IsRequired()
					.HasColumnType("longtext");

				b.Property<DateTime>("Fecha")
					.HasColumnType("datetime(6)");

				b.Property<string>("Estado")
					.IsRequired()
					.HasColumnType("longtext");

				b.Property<int>("ClienteId")
					.HasColumnType("int");

				b.HasKey("Id");

				b.HasIndex("ClienteId");

				b.ToTable("ServiciosPosVenta");
			});
			modelBuilder.Entity("ConcesionariaVehiculos.Models.Venta", b =>
			{
				b.HasOne("ConcesionariaVehiculos", "Cliente")
					.WithMany()
					.HasForeignKey("ClienteId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.HasOne("ConcesionariaVehiculos", "Vehiculo")
					.WithMany()
					.HasForeignKey("VehiculoId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("Cliente");

				b.Navigation("Vehiculo");
			});
#pragma warning restore 612, 618
		}
	}
}