// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ConcesionariaVehiculos.Data;

#nullable disable

namespace ConcesionariaVehiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConcesionariaVehiculos.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Apellido")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("Telefono")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)");

                b.HasKey("Id");

                b.ToTable("Clientes", (string)null);
            });

            modelBuilder.Entity("ConcesionariaVehiculos.ServicioPosVenta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ClienteId")
                    .HasColumnType("int");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime(6)");

                b.Property<string>("TipoServicio")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.HasIndex("ClienteId");

                b.ToTable("ServiciosPosVenta", (string)null);

            });

            modelBuilder.Entity("ConcesionariaVehiculos.Vehiculo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Año")
                    .HasColumnType("int");

                b.Property<string>("Marca")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("Modelo")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<decimal>("Precio")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Vehiculos", (string)null);


            });

            modelBuilder.Entity("ConcesionariaVehiculos.Venta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ClienteId")
                    .HasColumnType("int");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime(6)");

                b.Property<decimal>("Total")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("VehiculoId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ClienteId");

                b.HasIndex("VehiculoId");

                b.ToTable("Ventas", (string)null);


            });

            modelBuilder.Entity("ConcesionariaVehiculos.ServicioPosVenta", b =>
            {
                b.HasOne("ConcesionariaVehiculos.Cliente", null)
                    .WithMany()
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("ConcesionariaVehiculos.Venta", b =>
            {
                b.HasOne("ConcesionariaVehiculos.Models.Cliente", null)
                    .WithMany()
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ConcesionariaVehiculos.Models.Vehiculo", null)
                    .WithMany()
                    .HasForeignKey("VehiculoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}